name: "🔧 Backend Issue Report"
description: "Create a detailed report to help us improve the backend services."
title: "BACKEND ISSUE:"
labels: ["Backend", "Bug"]
body:
  - type: checkboxes
    attributes:
      label: "Preliminary Checks"
      description: "Please confirm the following before reporting a backend issue."
      options:
        - label: "I have checked the server logs"
          required: true
        - label: "I have searched the existing issues"
          required: true
  - type: textarea
    attributes:
      label: "Issue Summary"
      description: "Provide a concise summary of the issue, including what you expected to happen and what actually happened."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue. Include specific details, such as API endpoints, request parameters, etc."
    validations:
      required: true
  - type: textarea
    attributes:
      label: "Expected vs Actual Behavior"
      description: "What did you expect to happen instead of the current behavior?"
    validations:
      required: false
  - type: textarea
    attributes:
      label: "Logs/Errors"
      description: "If applicable, attach logs or error messages that can help us diagnose the issue."
    validations:
      required: false
  - type: checkboxes
    attributes:
      label: "Additional Information"
      options:
        - label: "I agree to follow this project's Code of Conduct"
          required: true
        - label: "I can provide more details if needed"
